const xs: number[] = [5, 12, 8, 1, 12];
console.log(xs.findLast((x) => x > 6));
console.log(xs.findLast((x) => x > 100));
console.log(xs.findLastIndex((x) => x === 12));
console.log(xs.findLastIndex((x) => x === 99));
console.log(xs.toReversed());
console.log(xs);
console.log(xs.toSorted());
console.log(xs.toSorted((a, b) => a - b));
console.log(xs);
console.log(xs.toSpliced(1, 2));
console.log(xs);
console.log(xs.toString());
console.log([1.5, -0, 7].toString());
console.log(xs.with(0, 99));
console.log(xs.with(-1, 42));
console.log(xs);
const strs: string[] = ['b', 'a'];
console.log(strs.toSorted());
console.log(strs.toString());
