/* `--emit=lib` (plan.md §10 Task 7.4, docs/FFI.md §8): the pure pieces of `cli/library.ts`, the
 * refusals (STA0004, STA1219, STA1220), and the config key. The end-to-end proof -- a consumer
 * built from only the `.a`, `.h` and `.pc`, two libraries in one program, byte-identical
 * archives -- is `ffi/example-c-consumer/static-lib.ts`, which the ffi and ASan CI jobs run. */

import { strict as assert } from 'node:assert';
import { spawnSync } from 'node:child_process';
import { existsSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { test } from 'vitest';
import { build } from '../../compiler/src/cli/build.ts';
import { type CliOptions, loadConfig, resolveOptions } from '../../compiler/src/cli/config.ts';
import {
  archiverCall,
  keptSymbolsText,
  libraryName,
  objectFormat,
  pkgConfigPath,
  prelinkArgs,
  renderPkgConfig,
} from '../../compiler/src/cli/library.ts';
import { EXPORT_ABI_VERSION } from '../../compiler/src/frontend/export.ts';
import { BuildError } from '../../compiler/src/support/diagnostics.ts';

const CLI = fileURLToPath(new URL('../../compiler/src/cli/main.ts', import.meta.url));

function scratch(files: Record<string, string>): string {
  const dir = mkdtempSync(join(tmpdir(), 'stator-static-lib-'));
  for (const [name, text] of Object.entries(files)) {
    writeFileSync(join(dir, name), text);
  }
  return dir;
}

function statorBuild(args: readonly string[]): { status: number | null; stderr: string } {
  const run = spawnSync(process.execPath, [CLI, 'build', ...args], { encoding: 'utf8' });
  return { status: run.status, stderr: run.stderr };
}

test('libraryName takes only lib<name>.a, the spelling -l<name> finds', () => {
  assert.equal(libraryName('out/libconsumer.a'), 'consumer');
  assert.equal(libraryName('libmy-lib.2.a'), 'my-lib.2');
  assert.equal(libraryName('consumer.a'), undefined);
  assert.equal(libraryName('libconsumer.so'), undefined);
  assert.equal(libraryName('lib.a'), undefined);
  assert.equal(
    pkgConfigPath(join('out', 'libconsumer.a'), 'consumer'),
    join('out', 'libconsumer.pc'),
  );
});

test('object format: Mach-O on macOS, ELF elsewhere, none on Windows (STA1219)', () => {
  assert.equal(objectFormat('darwin'), 'macho');
  assert.equal(objectFormat('linux'), 'elf');
  assert.equal(objectFormat('freebsd'), 'elf');
  assert.equal(objectFormat('win32'), undefined);
});

test('the keep list spells C names the way each format does', () => {
  assert.equal(keptSymbolsText('macho', ['stator_u_init', 'x']), '_stator_u_init\n_x\n');
  assert.equal(keptSymbolsText('elf', ['stator_u_init', 'x']), 'stator_u_init\nx\n');
});

test('the prelink: no clang config file, archives after the object, debug info dropped', () => {
  const macho = prelinkArgs('macho', 'u.o', ['std.a', 'jsrt.a'], 'keep.txt', 'p.o', false);
  assert.deepEqual(macho, [
    '--no-default-config',
    '-r',
    '-nostdlib',
    'u.o',
    'std.a',
    'jsrt.a',
    '-Wl,-exported_symbols_list,keep.txt',
    '-Wl,-S',
    '-o',
    'p.o',
  ]);
  // ELF localizes with objcopy after the link, so the link itself takes no list.
  const elf = prelinkArgs('elf', 'u.o', ['jsrt.a'], 'keep.txt', 'p.o', true);
  assert.deepEqual(elf, ['--no-default-config', '-r', '-nostdlib', 'u.o', 'jsrt.a', '-o', 'p.o']);
});

test('the archiver runs in its deterministic mode on both formats', () => {
  assert.deepEqual(archiverCall('elf', 'l.a', 'm.o'), { args: ['rcsD', 'l.a', 'm.o'], env: {} });
  assert.deepEqual(archiverCall('macho', 'l.a', 'm.o'), {
    args: ['rcs', 'l.a', 'm.o'],
    env: { ZERO_AR_DATE: '1' },
  });
});

test('the .pc is relocatable and carries the binary link list in Libs', () => {
  const beside = renderPkgConfig({
    name: 'consumer',
    unit: 'consumer',
    includeDir: '',
    libs: ['-L/opt/gc/lib', '-lgc', '-lm'],
  });
  assert.equal(
    beside,
    [
      '# Generated by `stator build --emit=lib` for unit `consumer` (docs/FFI.md §8).',
      'prefix=${pcfiledir}',
      'libdir=${prefix}',
      'includedir=${prefix}',
      '',
      'Name: libconsumer',
      'Description: Stator unit consumer as a static library with a private runtime',
      `Version: ${String(EXPORT_ABI_VERSION)}`,
      'Cflags: -I${includedir}',
      'Libs: -L${libdir} -lconsumer -L/opt/gc/lib -lgc -lm',
      '',
    ].join('\n'),
  );
  // A header elsewhere is named relative to the .pc, its separators escaped for pkg-config.
  const apart = renderPkgConfig({ name: 'u', unit: 'u', includeDir: '../my include', libs: [] });
  assert.match(apart, /^includedir=\$\{prefix\}\/\.\.\/my\\ include$/m);
});

test('--emit=lib refuses a missing header and an -o that is not lib<name>.a (STA0004)', () => {
  const dir = scratch({ 'u.ts': 'export function one(): number {\n  return 1;\n}\n' });
  try {
    const noHeader = statorBuild([join(dir, 'u.ts'), '--emit=lib', '-o', join(dir, 'libu.a')]);
    assert.equal(noHeader.status, 1);
    assert.match(noHeader.stderr, /STA0004/);
    assert.match(noHeader.stderr, /--emit=lib requires --emit-header/);
    const badName = statorBuild([
      join(dir, 'u.ts'),
      '--emit=lib',
      '-o',
      join(dir, 'u.a'),
      `--emit-header=${join(dir, 'u.h')}`,
    ]);
    assert.equal(badName.status, 1);
    assert.match(badName.stderr, /STA0004/);
    assert.match(badName.stderr, /-o lib<name>\.a/);
    assert.equal(existsSync(join(dir, 'u.h')), false, 'refused before anything is written');
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

// Windows refuses --emit=lib before compiling (STA1219, the next test), so STA1220 cannot arise there.
test(
  'an export that crosses as jsrt_value is STA1220 under --emit=lib only',
  { skip: process.platform === 'win32' },
  () => {
    const dir = scratch({
      'u.ts': 'export function kind(x: unknown): string {\n  return typeof x;\n}\n',
    });
    try {
      const refused = statorBuild([
        join(dir, 'u.ts'),
        '--emit=lib',
        '-o',
        join(dir, 'libu.a'),
        `--emit-header=${join(dir, 'u.h')}`,
      ]);
      assert.equal(refused.status, 1);
      assert.match(refused.stderr, /STA1220/);
      assert.equal(existsSync(join(dir, 'libu.a')), false);
      assert.equal(existsSync(join(dir, 'u.h')), false);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  },
);

test('--emit=lib on Windows is STA1219, before compiling', async () => {
  const platform = Object.getOwnPropertyDescriptor(process, 'platform');
  assert.ok(platform);
  Object.defineProperty(process, 'platform', { ...platform, value: 'win32' });
  try {
    await assert.rejects(
      build({
        entry: 'never-read.ts',
        out: 'libu.a',
        mode: 'ts',
        emitCOnly: false,
        keepC: false,
        emitHeader: 'u.h',
        emitLib: true,
      }),
      (error: unknown) => error instanceof BuildError && error.code === 'STA1219',
    );
  } finally {
    Object.defineProperty(process, 'platform', platform);
  }
});

test('config "emit": "lib" resolves like --emit=lib', () => {
  const cli: CliOptions = {
    entry: undefined,
    out: undefined,
    mode: undefined,
    opt: undefined,
    link: [],
    emit: undefined,
    keepC: undefined,
    emitHeader: undefined,
    unitName: undefined,
    bundler: undefined,
    diagnostics: undefined,
    node: undefined,
  };
  // Through the loader, so the schema is what accepts the value.
  const dir = scratch({ 'stator.config.json': '{ "emit": "lib" }' });
  try {
    const file = loadConfig({ kind: 'discover' }, dir);
    assert.equal(resolveOptions(cli, { opt: undefined }, file).emit, 'lib');
    assert.equal(
      resolveOptions({ ...cli, emit: 'binary' }, { opt: undefined }, file).emit,
      'binary',
    );
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});
