// GENERATED by ffi-gen (plan.md §10 Task 7.3) from sqlite_mini.h — do not edit.
// Regenerate: node packages/compiler/src/ffi-gen/main.ts <header.h> [--out=<file>]
// 13 emitted, 0 refused from sqlite_mini.h.
// Error conventions are NEVER inferred — audit each function and add @statorError by hand
// (NOTES.md "comparisons are plain values"; the generator cannot tell 100/101 from failure).
// C `int`-family widens to `number` (the i32 refinement has no declaration spelling).
// @statorLink: -lsqlite3
// @statorLink #include "./sqlite_mini.h"

// Borrowed NUL-terminated UTF-8 at the FFI boundary (docs/FFI.md §3).
type CString = string & { readonly __statorCstr: 'CString' };

// Out-param slot: the caller allocates the wrapper, the callee writes `value` on success.
type Out<T> = { readonly value: T };

/** Opaque `C sqlite3` handle (generated brand; lifetime belongs to the C library). */
type Ptr_sqlite3 = { readonly __brand: 'sqlite3' };

/** Opaque `C sqlite3_stmt` handle (generated brand; lifetime belongs to the C library). */
type Ptr_sqlite3_stmt = { readonly __brand: 'sqlite3_stmt' };

// C: int (sqlite3_stmt *, int, double) — from sqlite_mini.h:41
// Ownership (generated): `p0` borrowed opaque for the call. No error convention inferred.
/** @statorExtern sqlite3_bind_double */
declare function sqlite3BindDouble(p0: Ptr_sqlite3_stmt, p1: number, p2: number): number;

// C: int (sqlite3_stmt *, int, int) — from sqlite_mini.h:39
// Ownership (generated): `p0` borrowed opaque for the call. No error convention inferred.
/** @statorExtern sqlite3_bind_int */
declare function sqlite3BindInt(p0: Ptr_sqlite3_stmt, p1: number, p2: number): number;

// C: int (sqlite3 *) — from sqlite_mini.h:51
// Ownership (generated): `p0` borrowed opaque for the call. No error convention inferred.
/** @statorExtern sqlite3_changes */
declare function sqlite3Changes(p0: Ptr_sqlite3): number;

// C: int (sqlite3 *) — from sqlite_mini.h:45
// Ownership (generated): `p0` borrowed opaque for the call. No error convention inferred.
/** @statorExtern sqlite3_close */
declare function sqlite3Close(p0: Ptr_sqlite3): number;

// C: double (sqlite3_stmt *, int) — from sqlite_mini.h:35
// Ownership (generated): `p0` borrowed opaque for the call. No error convention inferred.
/** @statorExtern sqlite3_column_double */
declare function sqlite3ColumnDouble(p0: Ptr_sqlite3_stmt, iCol: number): number;

// C: int (sqlite3_stmt *, int) — from sqlite_mini.h:33
// Ownership (generated): `p0` borrowed opaque for the call. No error convention inferred.
/** @statorExtern sqlite3_column_int */
declare function sqlite3ColumnInt(p0: Ptr_sqlite3_stmt, iCol: number): number;

// C: const unsigned char * (sqlite3_stmt *, int) — from sqlite_mini.h:37
// Ownership (generated): `p0` borrowed opaque for the call; return copied to a fresh string at the boundary. No error convention inferred.
/** @statorExtern sqlite3_column_text */
declare function sqlite3ColumnText(p0: Ptr_sqlite3_stmt, iCol: number): CString;

// C: const char * (sqlite3 *) — from sqlite_mini.h:47
// Ownership (generated): `p0` borrowed opaque for the call; return copied to a fresh string at the boundary. No error convention inferred.
/** @statorExtern sqlite3_errmsg */
declare function sqlite3Errmsg(p0: Ptr_sqlite3): CString;

// C: int (sqlite3_stmt *) — from sqlite_mini.h:43
// Ownership (generated): `pStmt` borrowed opaque for the call. No error convention inferred.
/** @statorExtern sqlite3_finalize */
declare function sqlite3Finalize(pStmt: Ptr_sqlite3_stmt): number;

// C: int () — from sqlite_mini.h:49
// Ownership (generated): none — value copies in, plain value out. No error convention inferred.
/** @statorExtern sqlite3_libversion_number */
declare function sqlite3LibversionNumber(): number;

// C: int (const char *, sqlite3 **) — from sqlite_mini.h:18
// Ownership (generated): `filename` borrowed for the call; `ppDb` out-param written on success. No error convention inferred.
/** @statorExtern sqlite3_open */
declare function sqlite3Open(filename: CString, ppDb: Out<Ptr_sqlite3>): number;

// C: int (sqlite3 *, const char *, int, sqlite3_stmt **, const char **) — from sqlite_mini.h:23
// Ownership (generated): `db` borrowed opaque, `zSql` borrowed for the call; `ppStmt` out-param written on success, `pzTail` out-param written on success. No error convention inferred.
/** @statorExtern sqlite3_prepare_v2 */
declare function sqlite3PrepareV2(
  db: Ptr_sqlite3,
  zSql: CString,
  nByte: number,
  ppStmt: Out<Ptr_sqlite3_stmt>,
  pzTail: Out<CString>,
): number;

// C: int (sqlite3_stmt *) — from sqlite_mini.h:31
// Ownership (generated): `p0` borrowed opaque for the call. No error convention inferred.
/** @statorExtern sqlite3_step */
declare function sqlite3Step(p0: Ptr_sqlite3_stmt): number;

// No refusals — every declaration in sqlite_mini.h mapped.
