/* Test262 feature tags are a projection of docs/SUBSET.md, never a second subset authority. */

export type FeatureStatus =
  | { readonly kind: 'supported'; readonly row: string }
  | { readonly kind: 'not-yet'; readonly code: string; readonly row: string }
  | { readonly kind: 'never'; readonly row: string };

const SUPPORTED: Readonly<Record<string, string>> = {
  Array: 'Array.prototype row in docs/SUBSET.md',
  Date: 'Date row in docs/SUBSET.md',
  JSON: 'JSON.parse and JSON.stringify rows in docs/SUBSET.md',
  Math: 'Math row in docs/SUBSET.md',
  Object: 'Object row in docs/SUBSET.md',
  Promise: 'Promise row in docs/SUBSET.md',
  RegExp: 'RegExp row in docs/SUBSET.md',
  String: 'String.prototype row in docs/SUBSET.md',
  'array-methods': 'Array.prototype row in docs/SUBSET.md',
  'arrow-functions': 'Function declarations and arrow functions row in docs/SUBSET.md',
  'async-functions': 'async function row in docs/SUBSET.md',
  'block-scoping': 'let, const bindings row in docs/SUBSET.md',
  classes: 'Classes with fixed shape row in docs/SUBSET.md',
  'computed-property-names': 'Object literal forms row in docs/SUBSET.md',
  'default-parameters': 'Default parameter values row in docs/SUBSET.md',
  destructuring: 'Object and array destructuring rows in docs/SUBSET.md',
  'destructuring-binding': 'Object and array destructuring rows in docs/SUBSET.md',
  'for-in': 'for-in loop row in docs/SUBSET.md',
  'for-of': 'for-of loop row in docs/SUBSET.md',
  generators: 'Generator functions and yield row in docs/SUBSET.md',
  Map: 'Map row in docs/SUBSET.md',
  Set: 'Set row in docs/SUBSET.md',
  'template-literals': 'Template literals row in docs/SUBSET.md',
  'object-rest': 'Object literal forms row in docs/SUBSET.md',
  'object-spread': 'Object literal forms row in docs/SUBSET.md',
  'optional-catch-binding': 'try/catch/finally row in docs/SUBSET.md',
  'promise-prototype-finally': 'Promise.prototype row in docs/SUBSET.md',
  'regexp-dotall': 'RegExp row in docs/SUBSET.md',
  'regexp-lookbehind': 'RegExp row in docs/SUBSET.md',
  'regexp-named-groups': 'RegExp row in docs/SUBSET.md',
  'regexp-unicode-property-escapes': 'RegExp row in docs/SUBSET.md',
  'rest-parameters': 'Rest parameters row in docs/SUBSET.md',
  'symbol-description': 'Symbol row in docs/SUBSET.md',
  'top-level-await': 'Top-level await row in docs/SUBSET.md',
};

const NOT_YET: Readonly<Record<string, { readonly code: string; readonly row: string }>> = {
  BigInt: { code: 'STA1213', row: 'BigInt row in docs/SUBSET.md' },
  'async-generators': {
    code: 'STA1201',
    row: 'Generator functions and yield row in docs/SUBSET.md',
  },
  'for-await-of': { code: 'STA1201', row: 'for-of loop row in docs/SUBSET.md' },
  'dynamic-import': { code: 'STA1207', row: 'import() dynamic import row in docs/SUBSET.md' },
  'import-attributes': { code: 'STA1207', row: 'import() dynamic import row in docs/SUBSET.md' },
  'private-methods': { code: 'STA1214', row: 'Class member surface row in docs/SUBSET.md' },
  Symbol: { code: 'STA1212', row: 'Symbol row in docs/SUBSET.md' },
  'Symbol.iterator': { code: 'STA1212', row: 'Symbol row in docs/SUBSET.md' },
  'regexp-match-indices': { code: 'STA1211', row: 'RegExp row in docs/SUBSET.md' },
  Proxy: { code: 'STA1203', row: 'Proxy row in docs/SUBSET.md' },
  __proto__: { code: 'STA1204', row: 'Prototype mutation row in docs/SUBSET.md' },
  'Reflect.setPrototypeOf': {
    code: 'STA1204',
    row: 'Prototype mutation row in docs/SUBSET.md',
  },
};

// These tags occur in the pinned corpus but describe a semantic surface wider than Stator's
// corresponding partial implementation. Keeping the list closed makes a corpus bump visible:
// a new tag still reaches the undefined result below and fails the runner.
const GENERIC_NOT_YET_FEATURES = [
  'AggregateError',
  'Array.fromAsync',
  'Array.prototype.at',
  'Array.prototype.flat',
  'Array.prototype.flatMap',
  'Array.prototype.includes',
  'Array.prototype.values',
  'ArrayBuffer',
  'Atomics',
  'Atomics.pause',
  'Atomics.waitAsync',
  'DataView',
  'DataView.prototype.getFloat32',
  'DataView.prototype.getFloat64',
  'DataView.prototype.getInt16',
  'DataView.prototype.getInt32',
  'DataView.prototype.getInt8',
  'DataView.prototype.getUint16',
  'DataView.prototype.getUint32',
  'DataView.prototype.setUint8',
  'Error.isError',
  'FinalizationRegistry',
  'Float16Array',
  'Float32Array',
  'Float64Array',
  'Int16Array',
  'Int32Array',
  'Int8Array',
  'Intl-enumeration',
  'Intl.DateTimeFormat-datetimestyle',
  'Intl.DateTimeFormat-dayPeriod',
  'Intl.DateTimeFormat-extend-timezonename',
  'Intl.DateTimeFormat-formatRange',
  'Intl.DateTimeFormat-fractionalSecondDigits',
  'Intl.DisplayNames',
  'Intl.DisplayNames-v2',
  'Intl.DurationFormat',
  'Intl.Era-monthcode',
  'Intl.ListFormat',
  'Intl.Locale',
  'Intl.Locale-info',
  'Intl.NumberFormat-unified',
  'Intl.NumberFormat-v3',
  'Intl.RelativeTimeFormat',
  'Intl.Segmenter',
  'IsHTMLDDA',
  'Iterator.prototype.join',
  'Math.sumPrecise',
  'Object.fromEntries',
  'Object.hasOwn',
  'Object.is',
  'Promise.allSettled',
  'Promise.any',
  'Promise.prototype.finally',
  'Reflect',
  'Reflect.construct',
  'Reflect.set',
  'Reflect.setPrototypeOf',
  'RegExp.escape',
  'ShadowRealm',
  'SharedArrayBuffer',
  'String.fromCodePoint',
  'String.prototype.at',
  'String.prototype.endsWith',
  'String.prototype.includes',
  'String.prototype.isWellFormed',
  'String.prototype.matchAll',
  'String.prototype.replaceAll',
  'String.prototype.toWellFormed',
  'String.prototype.trimEnd',
  'String.prototype.trimStart',
  'Symbol.asyncIterator',
  'Symbol.hasInstance',
  'Symbol.isConcatSpreadable',
  'Symbol.match',
  'Symbol.matchAll',
  'Symbol.prototype.description',
  'Symbol.replace',
  'Symbol.search',
  'Symbol.species',
  'Symbol.split',
  'Symbol.toPrimitive',
  'Symbol.toStringTag',
  'Symbol.unscopables',
  'Temporal',
  'TypedArray',
  'TypedArray.prototype.at',
  'Uint16Array',
  'Uint32Array',
  'Uint8Array',
  'Uint8ClampedArray',
  'WeakMap',
  'WeakRef',
  'WeakSet',
  '__getter__',
  '__proto__',
  '__setter__',
  'align-detached-buffer-semantics-with-web-reality',
  'arbitrary-module-namespace-names',
  'array-find-from-last',
  'array-grouping',
  'arraybuffer-transfer',
  'arrow-function',
  'async-iteration',
  'await-dictionary',
  'caller',
  'canonical-tz',
  'change-array-by-copy',
  'class',
  'class-fields-private',
  'class-fields-private-in',
  'class-fields-public',
  'class-methods-private',
  'class-static-block',
  'class-static-fields-private',
  'class-static-fields-public',
  'class-static-methods-private',
  'coalesce-expression',
  'const',
  'cross-realm',
  'decorators',
  'destructuring-assignment',
  'error-cause',
  'error-stack-accessor',
  'explicit-resource-management',
  'exponentiation',
  'export-star-as-namespace-from-module',
  'for-in-order',
  'globalThis',
  'hashbang',
  'host-gc-required',
  'immutable-arraybuffer',
  'import-bytes',
  'import-defer',
  'import-text',
  'import.meta',
  'intl-normative-optional',
  'iterator-chunking',
  'iterator-helpers',
  'iterator-includes',
  'iterator-sequencing',
  'joint-iteration',
  'json-modules',
  'json-parse-with-source',
  'json-superset',
  'legacy-regexp',
  'let',
  'logical-assignment-operators',
  'new.target',
  'nonextensible-applies-to-private',
  'numeric-separator-literal',
  'optional-chaining',
  'promise-try',
  'promise-with-resolvers',
  'proxy-missing-checks',
  'regexp-duplicate-named-groups',
  'regexp-modifiers',
  'regexp-v-flag',
  'resizable-arraybuffer',
  'set-methods',
  'source-phase-imports',
  'source-phase-imports-module-source',
  'stable-array-sort',
  'stable-typedarray-sort',
  'string-trimming',
  'super',
  'symbols-as-weakmap-keys',
  'tail-call-optimization',
  'template',
  'u180e',
  'uint8array-base64',
  'upsert',
  'well-formed-json-stringify',
] as const;

const GENERIC_NOT_YET: Readonly<Record<string, { readonly code: string; readonly row: string }>> =
  Object.fromEntries(
    GENERIC_NOT_YET_FEATURES.map((feature) => [
      feature,
      {
        code: 'STA1214',
        row: 'Test262 feature-tag coverage row in docs/SUBSET.md',
      },
    ]),
  );

const NEVER: Readonly<Record<string, string>> = {
  decorators: 'Decorators row in docs/SUBSET.md',
  eval: 'eval() function row in docs/SUBSET.md',
  'with-statement': 'with statement row in docs/SUBSET.md',
};

export function featureStatus(feature: string): FeatureStatus | undefined {
  const supported = Object.hasOwn(SUPPORTED, feature) ? SUPPORTED[feature] : undefined;
  if (supported !== undefined) {
    return { kind: 'supported', row: supported };
  }
  const notYet = Object.hasOwn(NOT_YET, feature) ? NOT_YET[feature] : GENERIC_NOT_YET[feature];
  if (notYet !== undefined) {
    return { kind: 'not-yet', ...notYet };
  }
  const never = Object.hasOwn(NEVER, feature) ? NEVER[feature] : undefined;
  return never === undefined ? undefined : { kind: 'never', row: never };
}
